spring:
  config:
    activate:
      on-profile: default
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

database:
  url: jdbc:mysql://localhost/demo
  username: root
  password: 1234
  file:
    voucher: "voucher_simple_db.csv"
    black-list: "customer_blacklist.csv"

---

spring:
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
database:
  url: jdbc:mysql://localhost/demo
  username: root
  password: 1234
  file:
    black-list: "customer_blacklist.csv"

---

spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
database:
  url: jdbc:mysql://localhost/demo
  username: root
  password: 1234
  file:
    black-list: "customer_blacklist.csv"

---

spring:
  config:
    activate:
      on-profile: test
  devtools:
    livereload:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
database:
  url: jdbc:mysql://localhost/demo
  username: root
  password: 1234
  file:
    black-list: "customer_blacklist.csv"